pipeline {
    agent any
    tools {
        nodejs 'node-js-19.3'
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        skipDefaultCheckout()
    }
    stages {
        stage('Clean up') { 
            steps {
                deleteDir()
            }
        }
        stage('Clone') {
            steps {
                git credentialsId: '4f8dcf06-a320-4afd-914d-d7fa62be287c', url: 'simple-node-js-react-npm-app'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'ls -l'
            }
        }
    }
    //post {
    //    success {
    //        archiveArtifacts artifacts: 'my-go-app', followSymlinks: false 
    //    }
    //}
}
